server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: expenses-server
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
    contexts: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/expenses
    username: ${DB_LOG:postgres}
    password: ${DB_PASS:1}
    hikari:
      minimum-idle: 1
      minimum-pool-size: ${DB_POOL_SIZE:5}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:300000}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:10000}
      connection-test-query: SELECT 1


logging:
  config: classpath:logback-spring.xml
